spring:
  application:
    name: spring-security-jwt

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:

            non_contextual_creation: true
    show-sql: true

##logging settings
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
custom:
  properties:
    client-id: client_id
    client-secret: client_secret

## security
security:
  oauth2:
    resource:
      jwt:
        key-value: jwt_key_value